#!/usr/bin/env tsx
/**
 * Sync threat rules from the ATR (Agent Threat Rules) upstream project into
 * Sage's `threats/agent-layer.yaml`.
 *
 * This script is OPT-IN. It does not run automatically. The accompanying
 * GitHub Action (.github/workflows/atr-sync.yml) is also disabled by default;
 * a Sage maintainer must explicitly enable it to receive sync proposals.
 *
 * What this script does:
 *   1. Loads the ATR rules listed in `threats/.atr-bridge-config.yaml`
 *      (read from the installed `agent-threat-rules` npm package).
 *   2. Converts them via the `agent-threat-rules/converters/sage` API,
 *      which produces Sage-schema YAML.
 *   3. Writes the converted rules to a new file
 *      `threats/agent-layer.atr-generated.yaml` (NOT directly into the
 *      existing agent-layer.yaml — Sage maintainers review the generated
 *      file and decide what to merge).
 *
 * What this script does NOT do:
 *   - Modify Sage's existing rules.
 *   - Auto-merge anything.
 *   - Send telemetry. The conversion runs entirely on the local machine.
 *
 * The Sage maintainer remains the sole decision-maker on rule inclusion.
 * See docs/INTEROP.md for the full integration design.
 *
 * Usage:
 *   pnpm install agent-threat-rules
 *   pnpm exec tsx scripts/sync-with-atr.ts
 *
 * The script's only required dependency is the `agent-threat-rules` npm
 * package; it does not pull other Sage-internal modules.
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { parse as parseYaml } from 'yaml';

// The agent-threat-rules npm package exposes the converter at this subpath.
// Sage maintainers can pin a specific ATR version in package.json to get
// reproducible sync output.
import {
	atrToSageBatch,
	sageRulesToYaml,
	type SageRule,
} from 'agent-threat-rules/converters/sage';

interface AtrBridgeConfig {
	readonly enabled?: boolean;
	readonly atr_version?: string;
	readonly include_ids: readonly string[];
	readonly exclude_ids?: readonly string[];
	readonly manual_overrides?: readonly { id: string; reason: string }[];
	readonly starting_id_offsets?: Readonly<Record<string, number>>;
}

const CONFIG_PATH = join(process.cwd(), 'threats', '.atr-bridge-config.yaml');
const OUTPUT_PATH = join(process.cwd(), 'threats', 'agent-layer.atr-generated.yaml');

function loadConfig(): AtrBridgeConfig {
	if (!existsSync(CONFIG_PATH)) {
		throw new Error(
			`atr-bridge config not found at ${CONFIG_PATH}. ` +
				'See docs/INTEROP.md for the config schema.',
		);
	}
	const raw = readFileSync(CONFIG_PATH, 'utf-8');
	return parseYaml(raw) as AtrBridgeConfig;
}

async function loadAtrRulesFromNpm(ids: readonly string[]): Promise<any[]> {
	// The agent-threat-rules npm package ships ./rules/{category}/{id}.yaml
	// as static files. We load each by id.
	const atrPkgRoot = require.resolve('agent-threat-rules/package.json').replace(/\/package\.json$/, '');
	const { loadRuleFile } = await import('agent-threat-rules');
	const { readdirSync, statSync } = await import('node:fs');

	const rulesRoot = join(atrPkgRoot, 'rules');
	const found: any[] = [];
	for (const id of ids) {
		const subdirs = readdirSync(rulesRoot).filter((entry: string) =>
			statSync(join(rulesRoot, entry)).isDirectory(),
		);
		let path: string | null = null;
		outer: for (const sub of subdirs) {
			const dir = join(rulesRoot, sub);
			const files = readdirSync(dir);
			for (const f of files) {
				if (f.startsWith(`${id}-`) || f === `${id}.yaml`) {
					path = join(dir, f);
					break outer;
				}
			}
		}
		if (!path) {
			throw new Error(`ATR rule ${id} not found in installed agent-threat-rules package`);
		}
		found.push(loadRuleFile(path));
	}
	return found;
}

function buildHeader(config: AtrBridgeConfig, ruleCount: number): string {
	const now = new Date();
	const dateStr = `${now.getUTCFullYear()}-${String(now.getUTCMonth() + 1).padStart(2, '0')}-${String(now.getUTCDate()).padStart(2, '0')}`;
	const atrPkg = JSON.parse(
		readFileSync(require.resolve('agent-threat-rules/package.json'), 'utf-8'),
	) as { version: string };
	return `# Agent-layer threat patterns — auto-generated from ATR upstream
#
# Generated: ${dateStr}
# ATR version: ${atrPkg.version}
# Config: threats/.atr-bridge-config.yaml
# Rule count: ${ruleCount}
#
# DO NOT EDIT THIS FILE DIRECTLY.
# Sage maintainers: review the rules below, then copy desired entries into
# threats/agent-layer.yaml. This file is generated artifact, not source-of-
# truth.
#
# To regenerate: pnpm exec tsx scripts/sync-with-atr.ts
# To exclude a specific rule: add its ATR id to exclude_ids in the config.
# To override a generated rule: list it under manual_overrides in the config
# and edit the entry directly in threats/agent-layer.yaml (the sync script
# will skip overridden ids on future runs).
#
# License: Detection Rule License 1.1 (Sage threats/ convention).
# Upstream rules are MIT-licensed; provenance is preserved per-rule in
# the # Upstream: comment.
`;
}

async function main(): Promise<void> {
	const config = loadConfig();
	if (config.enabled === false) {
		console.error('[sync-with-atr] config.enabled is false — exiting');
		return;
	}

	const includeIds = config.include_ids ?? [];
	const excludeIds = new Set(config.exclude_ids ?? []);
	const overrideIds = new Set((config.manual_overrides ?? []).map((m) => m.id));
	const effectiveIds = includeIds.filter(
		(id) => !excludeIds.has(id) && !overrideIds.has(id),
	);

	if (effectiveIds.length === 0) {
		console.error('[sync-with-atr] no rules to sync after applying excludes/overrides');
		return;
	}

	console.error(`[sync-with-atr] syncing ${effectiveIds.length} ATR rules`);
	const atrRules = await loadAtrRulesFromNpm(effectiveIds);
	const { rules: sageRules, warnings } = atrToSageBatch(
		atrRules,
		config.starting_id_offsets ?? {},
	);

	if (warnings.length > 0) {
		console.error(`[sync-with-atr] ${warnings.length} conversion warnings:`);
		for (const w of warnings) {
			console.error(`  ${w.ruleId} [${w.kind}]: ${w.detail}`);
		}
	}

	const header = buildHeader(config, sageRules.length);
	const body = sageRulesToYaml(sageRules);
	mkdirSync(dirname(OUTPUT_PATH), { recursive: true });
	writeFileSync(OUTPUT_PATH, header + '\n' + body + '\n', 'utf-8');
	console.error(`[sync-with-atr] wrote ${sageRules.length} rules to ${OUTPUT_PATH}`);
	console.error('[sync-with-atr] review the file, then merge desired entries into agent-layer.yaml');
}

main().catch((err) => {
	console.error('[sync-with-atr] error:', err);
	process.exit(1);
});
